In [1]:
x=5
y=3
b=x*y
b

15

In [ ]:
a=x+y
a

c=y*y
c

In [ ]:
CH1="Go"
CH2="My"
CH3="Code"
CH=CH1+CH2+CH3
CH


In [ ]:
my_boolean = True

print(5 == 4)
print("hi" == "hi")


In [ ]:
age=11
age_min=12
if age>age_min:
    print("true")

if age<age_min:
    print("false")
    
elif age==11:
    print("one")
    
else :
    print("two")



In [ ]:
MyList= ["Web","AI","Game"]
print(MyList[0])
print(MyList)
print(len(MyList))

MyList.append("html")
print(MyList)

MyList.insert(1,"css")
print(MyList)

MyList.remove("AI")
print(MyList)

del MyList[0]
print(MyList)

In [ ]:
MyDict={"name":"jack","last name":"mccay","year":2019}
print(MyDict)

variable=MyDict["name"]
print(variable)

MyDict["year"]=2020
print(MyDict)

MyDict["survived"]="yes"
print(MyDict)

In [59]:
MyList= ["Web","AI","Game"]
for x in MyList:
    print(x)



Web
AI
Game


In [2]:
for x in range(0,10,10):
    print(x)

i=1
while i<6:
    print(i)
    i+=2

counter=0
while counter<3:
    print("inside loop")
    counter=counter+1
else:
    print("inside else")

0
1
3
5
inside loop
inside loop
inside loop
inside else


In [73]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

print(type(a))

value=np.random.random((2,3))
print(value)

value=np.random.randint(2,10, size=(2,5))
print(value)

value=np.full(5,3)
print(value)

value=np.eye(3,3)
print(value)

value=np.ones(3)
print(value)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[0.63617532 0.36221256 0.30465942]
 [0.28737743 0.7831178  0.53541152]]
[[8 8 5 8 9]
 [3 2 9 9 2]]
[3 3 3 3 3]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [2]:

Z=np.subt(x;y)
print(Z)

3
